FROM node:14-alpine

WORKDIR /home/dbgate-docker

RUN apk --no-cache upgrade \
 && apk --no-cache add  \
    iputils

COPY . .

RUN ["chmod", "+x", "/home/dbgate-docker/entrypoint.sh"]

WORKDIR /home/dbgate-docker

CMD ["/home/dbgate-docker/entrypoint.sh"]
